sudo: false

dist: trusty

language: ruby

cache:
  - bundler
  - pip
  - apt

install:
  - rake install

script:
  - rake test

addons:
  apt:
    packages:
    - python
    - python3-pip

# Only run tests on push on a few branches.
# Test on PR should be execute for all branches and forks.
branches:
  only:
  - master
